[package]
name = "app"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
imgui = "0.11.0"
imgui-glium-renderer = "0.11.0"
glium = "0.32.1"
imgui-winit-support = "0.11.0"
winit = "0.28.3"

[profile.release]
strip = true